# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# vi: ft=ruby

$:.unshift File.dirname(__FILE__)
require 'lib/utils.rb'

fastlane_version "1.3.0"

default_platform :iOS

platform :iOS do

  def run_tests(scheme)
    scan(
        scheme: scheme,
      )
      File.rename "../build/reports/report.junit", "../build/reports/#{scheme}-tests.xml"
  end

  before_all do
    ENV['DELIVER_WHAT_TO_TEST'] = git_commit_log
    ENV['SIGH_CERTIFICATE_ID'] = '9Q5433VBYW'
    GIT_BRANCH = ENV['GIT_BRANCH'] || 'unknown'

    GIT_BRANCH_ID = GIT_BRANCH.dup
    GIT_BRANCH_ID.gsub! '/', '.'
    GIT_BRANCH_ID.gsub! /[^A-Za-z0-9\-.]/, "-"

  end

  lane :pods do
    cocoapods(
      pod file: './hannatest'
    )
  end

  lane :tests do
    run_tests('hannatest')
  end

  lane :build do |options|

      project = 'hannatest/MaterialDesign.xcodeproj'

      increment_build_number(
        xcodeproj: project,
        build_number: ENV['BUILD_ID']
      )

      increment_version_number(
        xcodeproj: project,
        version_number: '1.4.1',
      )

      if options[:release]
        app_identifier = 'cogzidel.MaterialDesign'
        display_name = 'MaterialDesign'
        # Disable API server selection in settings app
        set_info_plist_value(
          path: './hannatest/MaterialDesign/Info.plist',
          key: 'isTest',
          value: false,
        )
        # Remove ability to load arbitrary TLS connections (may be added by developers)
        set_info_plist_value(
          path: './hannatest/MaterialDesign/Info.plist',
          key: 'NSAppTransportSecurity',
          value:  { 'NSAllowsArbitraryLoads' => false }
        )
        sigh(
          app_identifier: app_identifier,
        )
      else
        app_identifier = 'cogzidel.MaterialDesign.alpha.' + GIT_BRANCH_ID
        display_name = 'MaterialDesign' + GIT_BRANCH
        sigh(
          app_identifier: '*',
          adhoc: '1',
        )
      end

      update_app_identifier(
        app_identifier: app_identifier,
        plist_path: 'MaterialDesign/Info.plist',
        xcodeproj: 'hannatest/MaterialDesign.xcodeproj',
      )

      update_info_plist(
        display_name: display_name,
        plist_path: 'MaterialDesign/Info.plist',
        xcodeproj: 'hannatest/MaterialDesign.xcodeproj',
      )

      ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

      gym(
        scheme: options[:release] ? "MaterialDesign Release" : "MaterialDesign",
        configuration: options[:release] ? "Release" : "Beta",
        workspace: "hannatest/MaterialDesign.xcworkspace",
        cargos: '-derivedDataPath ./build',
        clean: false,
        use_legacy_build_api: true,
      )

  end

  lane :alpha do
    pods
    tests
    build_alpha
    deploy_alpha
  end

  lane :build_alpha do
    build(release: false)
  end

  lane :deploy_alpha do

    Actions.lane_context[SharedValues::IPA_OUTPUT_PATH] = './Nutrition.ipa'
    Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH] = './Nutrition.app.dSYM.zip'
    ENV['BUILD_ID'] = get_info_plist_value({ key: "CFBundleVersion", path: "Nutrition/Nutrition/Info.plist"})

    hockey(
      api_token: 'deadbeef',
      notes: git_commit_log,
      notify: '0', # Means do not notify
      status: '2',
      release_type: '2',
    )

    if ENV["SLACK_URL"]
      slack(
        message: "New alpha build available for download",
        success: true,
        payload: {
          'Build number' => ENV['BUILD_ID'],
          'Git branch' => ENV['GIT_BRANCH'],
          'Download URL' => Actions.lane_context[ Actions::SharedValues::HOCKEY_DOWNLOAD_LINK ],
          'What\'s new' => git_commit_log,
          },
        default_payloads: [],
     )
    end
  end

  lane :build_release do
    tests
    build(release: true)
  end

  end


